server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:    
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: gu
  password: 1234
  driver-class-name: oracle.jdbc.driver.OracleDriver
    
 thymeleaf:
  prefix : classpath:templates/
  suffix : .html
  cache : false
