server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

jwt:
 header: Authorization
 secret: rutyweorituwyerotiuweyrtoiuweyrtoweiurtywoeighdfsojkghsdfgsdofiguwyertouw | base64YWprbGdoc2Rma2xnanNkaGZnbGprc2RmZ2hsc2
 access-token-validity-in-seconds: 600 # 10 min
  
spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: gu
  password: 1234
  driver-class-name: oracle.jdbc.driver.OracleDriver

 thymeleaf:
  prefix : classpath:templates/
  suffix : .html
  cache : false
  
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
   map-underscore-to-camel-case: true
  type-aliases-package: com.gu.domain
  
