server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
  
spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: gu
  password: 1234
  driver-class-name: oracle.jdbc.driver.OracleDriver

 thymeleaf:
  prefix : classpath:templates/
  suffix : .html
  cache : false
  
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
   map-underscore-to-camel-case: true
  type-aliases-package: com.gu.domain
  
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400  # 초